# Generated by Django 3.0.6 on 2020-06-09 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200608_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'get_latest_by': '-todoDate', 'verbose_name': 'todo', 'verbose_name_plural': 'todos'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
