# Generated by Django 3.0.6 on 2020-06-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['todoDate'], 'verbose_name': 'todo', 'verbose_name_plural': 'todos'},
        ),
    ]
